### ISSUE TITLE
ResponsePropertyBecameOptionalCheck panics on property removal

### ISSUE THREAD

**Issue by blva** [oasdiff/oasdiff#188]
**Describe the bug**
ResponsePropertyBecameOptionalCheck throws a panic error on property removal

**To Reproduce**
1. Run `-base {source_path}/breaking-changes-test-spec-base.yaml -revision {source_path}/breaking-changes-test-spec-revision.yaml -deprecation-days=365 -check-breaking"`
2. With [base](https://pastebin.com/DmNvhFk4)
4. And [revision](https://pastebin.com/kWq3EqCb)
5. Recieve 
```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104753ad0]

goroutine 1 [running]:
github.com/tufin/oasdiff/checker.ResponsePropertyBecameOptionalCheck(0x14000306870, 0x140000109a8, {{0x140001648c0, 0x38, 0x38}, 0x1f, 0xb4, {{0x10491566e, 0x2}, {0x10491566e, ...}, ...}})
	/<redactedpath>/workplace/oasdiff/checker/check-response-property-became-optional.go:39 +0x5c0
github.com/tufin/oasdiff/checker.CheckBackwardCompatibility({{0x140001648c0, 0x38, 0x38}, 0x1f, 0xb4, {{0x10491566e, 0x2}, {0x10491566e, 0x2}, 0x1400007f5c0}}, ...)
	/<redactedpath>/workplace/oasdiff/checker/checker.go:118 +0x14c
main.main()
	/<redactedpath>/workplace/oasdiff/main.go:172 +0xdcc
```

6. **Expected behavior**
```shell
Backward compatibility errors (1):
error at /<redactedpath>/workplace/mms/server/openapi/atlas/breaking-changes-test-spec-revision.yaml, in API GET /api/atlas/v2/removeOutputFieldTest removed the required property 'name' from the response with the '200' status [response-required-property-removed]. 
```

**Desktop (please complete the following information):**
 - OS: `macOS Monterey`
 - Browser`chrome`
 - Version `oasdiff version: 1.3.4`

**Additional comments**
Opening a PR to fix it now

**Comment by reuvenharrison** [comment]
fixed by https://github.com/Tufin/oasdiff/pull/189
