### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by reuvenharrison** [oasdiff/oasdiff#406]
**Describe the bug**
There is a race-condition in `func strategy`:
Telemetry which is running in a go routine is using the cmd flags while `run` is simultaneously parsing the command-line.

**To Reproduce**
As a race-condition it is difficult to replicate this behavior but this is the error I got:
```
❯ oasdiff breaking ../data/openapi-test1.yaml ../data/openapi-test3.yaml --err-ignore ../data/ignore-err-example.txt --include-checks api-schema-removed
panic: runtime error: index out of range [1] with length 1

goroutine 6 [running]:
github.com/spf13/pflag.sortFlags(0xc000243260)
	/Users/Reuven/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:210 +0x1cf
github.com/spf13/pflag.(*FlagSet).Visit(0xc0001d9500, 0xc00006cf40)
	/Users/Reuven/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:328 +0x53
github.com/oasdiff/telemetry/client.fromCommand(0xc000004600)
	/Users/Reuven/go/pkg/mod/github.com/oasdiff/telemetry@v0.0.7/client/client.go:182 +0x12e
github.com/oasdiff/telemetry/client.(*Collector).Send(0xc000120000, 0x1631677?)
	/Users/Reuven/go/pkg/mod/github.com/oasdiff/telemetry@v0.0.7/client/client.go:44 +0x1b
github.com/tufin/oasdiff/internal.strategy.func1.1()
	/Users/Reuven/view/go/src/github.com/tufin/oasdiff/internal/run.go:83 +0x11e
created by github.com/tufin/oasdiff/internal.strategy.func1 in goroutine 1
	/Users/Reuven/view/go/src/github.com/tufin/oasdiff/internal/run.go:74 +0x78
```

**Comment by reuvenharrison** [comment]
Fixed by https://github.com/Tufin/oasdiff/pull/407
